### ISSUE TITLE
disclaimer - navigatie

### ISSUE THREAD

**Issue by PieterIng** [MakeInBelgium/hosting#10]
Wanneer je naar disclaimer gaat, weigert ie verdere navigatie.
bijvoorbeeld:
https://maakjemondmasker.be/disclaimer.html#maken
ipv
https://maakjemondmasker.be/#maken

**Comment by pbelmans** [comment]
Bedankt om het te melden! Het is gefixt, zie https://github.com/MakeInBelgium/naaiactie/pull/165
